# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BvrSbb8zUNFoUz3PCyw006HXZyp2t1m-

Création du fichier main.py qui est le point d'entrée unique. il importe tous les modules et expose un menu console interactif où chaque option appelle une fonction bien isolée.
"""

#Importation de toutes les classes
from models import User, Session, Program
from data_manager import DataManager, generate_simulated_data, generate_simulated_users, clean_dataset
from workout_generator import recommend_session
from scipy_analysis import test_anova_calories, regress_progress, ttest_paired
from visualizations import (graph_calories_over_time,
    graph_workout_frequency,
    graph_weekly_progression,
    generate_all_graphs)

current_user = None

#Fonction pour inscrire de nouveaux utilisateurs
def register_user(dm):
  print('--- Inscription ---')
  name = input('Nom : ').strip()
  age = int(input('Âge : ').strip())
  gender = input('Genre (M/F) : ').strip().upper()
  weight = float(input('Poids (kg) : ').strip())
  height = int(input('Taille (cm) : ').strip())
  goal = input('Objectif (perte_poids, force, cardio) : ').strip()
  new_user = User(user_id=dm.get_next_user_id(), name=name, age=age, weight=weight, height=height, goal=goal, gender=gender)
  print(f' Fitness Tracker IA — Bonjour {new_user.name} !')
  print(' IMC :', new_user.calculate_bmi(), '—', new_user.bmi_category())
  print(' Calories journalières estimées :', new_user.daily_calories())
  print('='*50)
  return new_user



# Menu principal
def menu():
  global current_user
  dm = DataManager()
  while True:
    print('\n' + '='*50) #
    print(' 1. Inscription')
    print(' 2. Connexion')
    print(' 3. Voir ma recommandation du jour')
    print(' 4. Afficher statistiques hebdomadaires')
    print(' 5. Analyses statistiques SciPy')
    print(' 6. Générer tous les graphiques')
    print(' 7. Mon programme de la semaine')
    print(' 8. Voir mon historique de séances')
    print(' 9. Générer des données de démonstration')
    print(' 0. Quitter')
    choix = input('\nVotre choix : ').strip()

     # df_clean chargé UNE SEULE FOIS à l'entrée du menu.
     # Toutes les options qui ont besoin du dataset nettoyé utilisent cette
     # variable commune au lieu d'appeler clean_dataset() à chaque action,
     # ce qui évite de recharger, retraiter et réafficher les stats à chaque choix,
     # ce qui rend le menu plus fluide. df_clean est rafraîchi uniquement après une génération de nouvelles données (choix absent ici car la génération se fait en __main__), ou si l'utilisateur le demande explicitement.
    df_clean = clean_dataset()
    
    if choix == '1':
      user = register_user(dm)
      dm.save_user(user)
      current_user = user

    elif choix == '2':
      if df_clean.empty:
        print("Aucune données à traiter. Veuillez d'abord générer des données.")
        continue
      while not current_user:
        name = input('Entrez votre nom pour vous connecter : ').strip()
        current_user = dm.find_user_by_name(name)
        if current_user:
          print(f'Bienvenue de nouveau, {current_user.name} !')
        else:
          print('Utilisateur non trouvé. Essayez à nouveau.')
    
    elif choix == '3':
      if current_user is None:
        print('Veuillez vous connnecter d\'abord.')
        continue

      
      if 'user_id' not in df_clean.columns:
        print("Aucune donnée utilisateur trouvée dans les séances.")
        continue
      df_user = dm.get_user_history(current_user.user_id, df_clean)
      
      # Si pas de données, recommander un programme débutant basé sur l'objectif
      if df_user.empty:
        if current_user.goal == "perte_poids":
          print("Programme débutant : marche rapide 30 min")

        elif current_user.goal == "force":
          print("Programme débutant : musculation légère")

        elif current_user.goal == "cardio":
          print("Programme débutant : jogging 20 min")
      else:
        rec = recommend_session(current_user, df_user)
        print(f'\nRecommandation : {rec["exercise"].capitalize()}'
        f' — {rec["duration"]} min')
        print(f'Conseil : {rec["message"]}')

    elif choix == '4':
      
      from data_manager import weekly_analysis
      print(weekly_analysis(df_clean).to_string(index=False))

    elif choix == '5':
      
      print('\n--- ANOVA ---')
      print(test_anova_calories(df_clean))
      print('\n--- Régression linéaire (calories) ---')
      print(regress_progress(df_clean, 'calories'))
      print('\n--- Test t apparié ---')
      print(ttest_paired(df_clean, 'calories'))

    elif choix == '6':
      
      graph_workout_frequency(df_clean)
      graph_weekly_progression(df_clean)
      graph_calories_over_time(df_clean)
      print('3 graphiques sauvegardés dans data/')

    elif choix == '7':
      
      if current_user is None:
        print('Veuillez vous connnecter d\'abord.')
        continue
      if 'user_id' not in df_clean.columns:
        print("Aucune donnée utilisateur trouvée dans les séances.")
        continue
      df_user = dm.get_user_history(current_user.user_id, df_clean)
      prog = Program(current_user)

      for jour in prog.generate_program():
        print(f" {jour['day']:10} {jour['exercise']:15} {jour['duration']} min"
      f" — {jour['intensity']}")

    elif choix == '8':
      if current_user is None:
        print("Veuillez vous connecter d'abord.")
        continue
      
      if df_clean is None or df_clean.empty:
        print("Aucune donnée disponible.")
        continue
      history = dm.get_user_history(current_user.user_id, df_clean)

      if history.empty:
        print("Aucune activité enregistrée.")
      else:
        print("\n=== HISTORIQUE D'ACTIVITES ===")
        print(history.to_string(index=False))

    elif choix == '9':
      generate_simulated_users(5) # Génère 5 utilisateurs de démonstration
      generate_simulated_data(days_nb=30) # Génère 30 jours de données pour tous les utilisateurs
      print("Données de démonstration générées dans data/")

    elif choix == '0':
      print('Au revoir !')
      break
if __name__ == '__main__':
  menu()
