# -*- coding: utf-8 -*-
"""scipy_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NrXIdYQWgBTQLYUnIZ-0gjLF07Hu_dkQ

Création du fichier scipy_analysis.py qui va tester s'il y a une différence significative de calories brûlées selon le type d'exercice. L'ANOVA à un facteur
(f_oneway) teste si les moyennes des groupes sont statistiquement différentes.
"""

import pandas as pd
import numpy as np
from scipy import stats

"""
ANOVA : teste si les calories diffèrent selon le type d'exercice.
H0 : toutes les moyennes sont égales.
H1 : au moins une moyenne est différente.
"""
def test_anova_calories(df):
  groupes = [
      df[
          df['workout_type'] == t]['calories']
          .dropna()
          .values
      for t in df['workout_type'].unique()
      if len(df[df['workout_type'] == t]) >= 3 # min 3 obs
      ]
  if len(groupes) < 2:
    return {'erreur': 'Données insuffisantes pour ANOVA'}
  stat_f, p_value = stats.f_oneway(*groupes)
  return {
      'test': 'ANOVA f_oneway',
      'F_statistic': round(stat_f, 4),
      'p_value': round(p_value, 6),
      'significatif': p_value < 0.05,
      'interpretation': (
      'Différence significative entre les types' if p_value < 0.05
      else 'Aucune différence significative (p >= 0.05)'
) }
# Utilisation :
# df = DataManager().charger_dataframe()
# resultat = test_anova_calories(df)
# print(resultat)

"""Création de la regression linéaire. Elle modélise la tendance sur les données passées pour prédire les pas ou les calories futures."""

def regress_progress(df, colonne='calories'):
  #Pour déterminer si l'utilisateur progresse
  """
Régression linéaire de 'colonne' en fonction du temps.
Retourne la pente (progression/jour), l'intercept et le R².
"""

  df_sorted = df.sort_values('date').reset_index(drop=True)
  x = np.arange(len(df_sorted)) # jours : 0, 1, 2 ...
  y = df_sorted[colonne].values
  print("Nombre de lignes :", len(df_sorted))
  print("NaN calories :", df_sorted[colonne].isna().sum())
  print(df_sorted[[colonne]].head())
  slope, intercept, r_value, p_value, std_err = stats.linregress(x, y)
  # Prédiction pour les 7 prochains jours
  futurs_days = np.arange(len(x), len(x) + 7)
  predictions = slope * futurs_days + intercept
  return {
      'test': 'Régression linéaire',
      'colonne': colonne,
      'pente': round(slope, 3), # variation par jour
      'intercept': round(intercept, 2),
      'r_squared': round(r_value**2, 4), # qualité du fit
      'p_value': round(p_value, 6),
      'predictions_7j': [round(p, 1) for p in predictions],
      'interpretation': (
      f'Progression de {slope:.1f} {colonne}/jour '
      f'(R²={r_value**2:.2f})'
      ) }

#T-test apparié pour comprarer les calories brulées avant et après un programme
def ttest_paired(df, colonne='calories', split_ratio=0.5):
  """
Test t apparié : première moitié vs deuxième moitié de l'historique.
Simule avant/après un programme d'entrainement.
"""
  df_sorted = df.sort_values('date')[colonne].dropna().values
  middle = int(len(df_sorted) * split_ratio)
  before = df_sorted[:middle]
  after = df_sorted[middle:middle + len(before)] # même taille
  if len(before) < 3 or len(after) < 3:
    return {'erreur': 'Pas assez de données (min 6 séances)'}
  t_stat, p_value = stats.ttest_rel(before, after)
  return {
  'test': 'Test t apparié',
  'colonne': colonne,
  'moyenne_avant': round(float(np.mean(before)), 1),
  'moyenne_apres': round(float(np.mean(after)), 1),
  'delta': round(float(np.mean(after) - np.mean(before)), 1),
  't_statistic': round(t_stat, 4),
  'p_value': round(p_value, 6),
  'significatif': p_value < 0.05,
  'interpretation': (
  f'Changement significatif de {colonne} (p={p_value:.4f})'
  if p_value < 0.05
  else f'Pas de changement significatif (p={p_value:.4f})'
  )}

if __name__ == '__main__':
  from data_manager import DataManager
  df = DataManager().load_dataframe()
  
  print(regress_progress(df, 'calories'))
  